### ISSUE TITLE
Warning: Invalid DOM property `class`. Did you mean `className`?

### ISSUE THREAD

**Issue by PrzemekCh** [wix-incubator/pro-gallery#883]
We're trying to use the component in our react 17.x app and we get some errors.

Some galery items don't work like Thrumbinalis active item selection - css is not applied on a selected card or Left Right arrows render randomly.

react-dom.development.js:67 Warning: Invalid DOM property `class`. Did you mean `className`?
    at div
    at ItemView (http://localhost/static/js/bundle.js:512624:24)
    at div
    at GroupView (http://localhost/static/js/bundle.js:510071:24)
    at div
    at div
    at div
    at div
    at SlideshowView (http://localhost/static/js/bundle.js:508777:24)
    at div
    at GalleryContainer (http://localhost/static/js/bundle.js:506874:24)
    at div
    at ProGallery (http://localhost/static/js/bundle.js:508664:24)
    at Gallery (http://localhost/static/js/bundle.js:506682:24)
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at AdDetails (http://localhost/static/js/bundle.js:3782:5)
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at section
    at EmotionCssPropInternal
    at render
    at FocusRing (http://localhost/static/js/bundle.js:67007:23)
    at render
    at EnteringMotion (http://localhost/static/js/bundle.js:74206:23)
    at FadeIn (http://localhost/static/js/bundle.js:74106:23)
    at div
    at EmotionCssPropInternal
    at Positioner (http://localhost/static/js/bundle.js:72863:24)
    at ModalDialog (http://localhost/static/js/bundle.js:72722:28)
    at div
    at EmotionCssPropInternal
    at Blanket (http://localhost/static/js/bundle.js:44723:36)
    at TouchScrollable (http://localhost/static/js/bundle.js:573706:5)
    at div
    at FocusLockUI (http://localhost/static/js/bundle.js:562903:60)
    at FocusLockUICombination
    at div
    at EmotionCssPropInternal
    at render
    at EnteringMotion (http://localhost/static/js/bundle.js:74206:23)
    at FadeIn (http://localhost/static/js/bundle.js:74106:23)
    at InternalPortal (http://localhost/static/js/bundle.js:76057:22)
    at Portal (http://localhost/static/js/bundle.js:76321:29)
    at ModalWrapper (http://localhost/static/js/bundle.js:73721:32)
    at http://localhost/static/js/bundle.js:73908:26
    at ModalTransition (http://localhost/static/js/bundle.js:73657:12)
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at AdVerticalCard (http://localhost/static/js/bundle.js:7182:5)
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at InfiniteScroll (http://localhost/static/js/bundle.js:12000:5)
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at FlexGrid (http://localhost/static/js/bundle.js:9656:5)
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at AdList (http://localhost/static/js/bundle.js:33540:64)
    at Route (http://localhost/static/js/bundle.js:573120:29)
    at Switch (http://localhost/static/js/bundle.js:573322:29)
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at div
    at http://localhost/static/js/bundle.js:116896:66
    at http://localhost/static/js/bundle.js:91752:25
    at div
    at EmotionCssPropInternal
    at div
    at EmotionCssPropInternal
    at div
    at EmotionCssPropInternal
    at Page (http://localhost/static/js/bundle.js:75451:32)
    at FlagsProvider (http://localhost/static/js/bundle.js:64860:23)
    at Router (http://localhost/static/js/bundle.js:572751:30)
    at BrowserRouter (http://localhost/static/js/bundle.js:572373:35)
    at AppRouter (http://localhost/static/js/bundle.js:42082:56)
    at ApolloProvider (http://localhost/static/js/bundle.js:605380:19)
    at ApolloContextProvider (http://localhost/static/js/bundle.js:23994:5)
    at ContextProvider (http://localhost/static/js/bundle.js:24328:5)
    at EnvironmentProvider (http://localhost/static/js/bundle.js:98655:24)
    at ColorModeProvider (http://localhost/static/js/bundle.js:85598:21)
    at ThemeProvider (http://localhost/static/js/bundle.js:116936:64)
    at ThemeProvider (http://localhost/static/js/bundle.js:104039:27)
    at http://localhost/static/js/bundle.js:89666:23
    at ChakraProvider (http://localhost/static/js/bundle.js:97950:24)
    at App

Plus errors like

WARNING in ./node modules/pro-gallery/dist/esm/components/item/videos/videoItemPlaceholder.is
Module Warning (from ./node modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/app/node modules/pro-gallery/src/components/item/videos/videoItemPlace
holder.js' file: Error: ENOENT: no such file or directory, open
*/home/app/node modules/pro-gallery/src/components/item/videos/videoItemPlaceh
older.js'

**Comment by yhattav** [comment]
Please reopen if this persists
